/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillsCompareRouteImport } from './routes/skills-compare'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as IndexRouteImport } from './routes/index'

const SkillsCompareRoute = SkillsCompareRouteImport.update({
  id: '/skills-compare',
  path: '/skills-compare',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/skills': typeof SkillsRoute
  '/skills-compare': typeof SkillsCompareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/skills': typeof SkillsRoute
  '/skills-compare': typeof SkillsCompareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/skills': typeof SkillsRoute
  '/skills-compare': typeof SkillsCompareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/skills' | '/skills-compare'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/skills' | '/skills-compare'
  id: '__root__' | '/' | '/skills' | '/skills-compare'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SkillsRoute: typeof SkillsRoute
  SkillsCompareRoute: typeof SkillsCompareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skills-compare': {
      id: '/skills-compare'
      path: '/skills-compare'
      fullPath: '/skills-compare'
      preLoaderRoute: typeof SkillsCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SkillsRoute: SkillsRoute,
  SkillsCompareRoute: SkillsCompareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
